### ISSUE TITLE
Performance issues on Safari and mobile

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/phasereditor2d-ninepatch-plugin#1]
![image](https://user-images.githubusercontent.com/758680/170363452-37cf1cde-18d2-4530-9a2b-e16af24895e0.png)

I created 100 sprites.

```
		for (let i = 0; i < 100; i++) {
			const obj = new NinePatch(this, 100, 100, 100, 100, "hud", "bt_pause.png");
			this.add.existing(obj);
```

**Comment by PhaserEditor2D** [comment]
Please, try using the NinePatchContainer or the NinePatchImage. The NinePatch object is really expensive.
